services:
  # === POSTS SERVICE ===
  posts-service:
    build: "C:/Users/glino/OneDrive/Рабочий стол/PostsPython"
    container_name: posts-service
    ports:
      - "8001:8000"  # внешний порт:порт внутри контейнера
    environment:
      - USERS_SERVICE_URL=http://fastapiproject2:8000
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=postworks_db
    volumes:
      - "C:/Users/glino/OneDrive/Рабочий стол/PostsPython:/app"
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # === MONGO DB ===
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: