version: "3.9"

services:
  posts-service:
    build: .
    container_name: posts-service
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - USERS_SERVICE_URL=http://users-service:8000
    depends_on:
      - mongo
      - users-service

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  users-service:
    image: users-service:latest
    container_name: users-service
    ports:
      - "8000:8000"